# Generated by Django 5.0.7 on 2024-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField()),
                ('from_place', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travelling_date', models.DateTimeField()),
                ('bus_type', models.CharField(choices=[('Ac', 'Ac'), ('Non-Ac', 'Non-Ac')], max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
